name = "tksports-api"
main = "worker.js"
compatibility_date = "2024-12-01"

# Dit heb je nodig voor fetch(), btoa(), etc.
compatibility_flags = ["nodejs_compat"]

[vars]
# Vul deze NIET in hier.
# Je zet ze in Cloudflare Dashboard → Workers → Settings → Variables
# MJ_APIKEY_PUBLIC = ""
# MJ_APIKEY_PRIVATE = ""
